export const CATEGORY_COLORS = [
    { name: "Red", code: "#EF4444" },
    { name: "Orange", code: "#F97316" },
    { name: "Amber", code: "#F59E0B" },
    { name: "Yellow", code: "#EAB308" },
    { name: "Lime", code: "#84CC16" },
    { name: "Green", code: "#22C55E" },
    { name: "Emerald", code: "#10B981" },
    { name: "Teal", code: "#14B8A6" },
    { name: "Cyan", code: "#06B6D4" },
    { name: "Sky", code: "#0EA5E9" },
    { name: "Blue", code: "#3B82F6" },
    { name: "Indigo", code: "#6366F1" },
    { name: "Violet", code: "#8B5CF6" },
    { name: "Purple", code: "#A855F7" },
    { name: "Fuchsia", code: "#D946EF" },
    { name: "Pink", code: "#EC4899" },
    { name: "Rose", code: "#F43F5E" },
    { name: "Parrot Green", code: "#6CF527" },
    { name: "Cyan Yellow", code: "#D3F527" },
    { name: "Blue", code: "#40B8DD" },
];